GET  http://35.188.169.72:5000 HTTP/1.1
content-type: application/json

### Bot

POST  http://35.188.169.72:5000/science HTTP/1.1
content-type: application/json

{
    "message": "what is newtons second law of motion"
}

# ---------------------------------------------------------------------

### Local

GET  http://127.0.0.1:5000/  HTTP/1.1
content-type: application/json

### Bot

POST  http://127.0.0.1:5000/science HTTP/1.1
content-type: application/json

{
    "message": "what is atom"
}
